alias vim=/opt/homebrew/bin/nvim
alias ta="tmux attach"
alias tls="tmux ls"
alias tnew="tmux new -s"
alias p="op run -- rootless-personio"
alias ls=lsd
alias cat=bat
alias grep=rg
alias gbr="git branch -a | grep -v \"^\*\"  | fzf | sed -r 's/remotes\/origin\///'| xargs git switch"
alias ghb="gh browse"
alias oil="nvim ."
alias lg="nvim -c 'G'"
alias fn="nvim -c 'Fzf files'"
alias db="nvim -c 'DBUI'"
alias today="nvim $HOME/todays/$(date '+%Y-%m-%d').md"
alias cc="claude"
