alias vim=nvim
alias ta="tmux attach"
alias tls="tmux ls"
alias tnew="tmux new -s"
alias u=dinkur
alias p="op run -- rootless-personio"
alias ls=lsd
alias cat=bat
alias grep=rg
alias gbr="git branch | grep -v \"^\*\" | fzf | xargs git switch"
alias ghb="gh browse"
